#!/usr/bin/env python3
"""Prefill the `verdict` column of the Biopython API inventory.

Step 0.1 produced a flat inventory of everything Biopython exposes; it says what
exists, not what is worth rewriting in C++.  This script closes that gap: it
reads `biopython_inventory.csv` and writes `biopython_triage.csv` -- the same
rows plus `verdict` and `reason`.

    python3 inventory/triage.py

Why a second file instead of a new column in the inventory itself: the inventory
is regenerated by `scan_biopython.py` whenever Biopython changes, and a rerun
overwrites the file outright.  Keeping verdicts in their own artifact means a
rescan never silently discards a judgement, and the two are joined on
(module, qualname, kind).

Verdicts
--------
    perf    hot path with a real speed gap -- this is a kernel to write.
    parity  worth having for drop-in compatibility, no large win expected.
    data    should become data plus a parser, never ported as code.
    skip    do not port.  Reserved for mechanical reasons only, see below.

`data` extends the perf/parity/skip vocabulary recorded in PLAN.md, because the
Restriction autogeneration and the codon tables are neither slow work nor API
parity work -- the plan's own answer for them is "data + parser".

The bias is deliberate: **skip requires a mechanical reason**, and anything
arguable is written down as work.  The reasons that qualify:

    1. flagged deprecated upstream (the inventory's own column),
    2. flagged deprecated in fact but not in the column (Bio.pairwise2),
    3. the object's job is to make a network request,
    4. the object's job is to launch another program,
    5. upstream already implements it in C, so a rewrite buys nothing,
    6. the work is owned by a numerical library (scipy fitting).

Everything else is at least `parity`.  A judgement call resolved towards "do the
work" costs a row in a list; resolved towards "skip" it costs a feature nobody
notices is missing until someone needs it.

This is a *prefill*, not a verdict: per the standing decision the owner validates
the contested rows.  The `reason` column is there to make that review cheap --
read the reasons, not the 3,595 rows.
"""

from __future__ import annotations

import csv
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "biopython_inventory.csv"
TARGET = HERE / "biopython_triage.csv"

# --- rule 3: the object's job is to make a network request -------------------
# Modules that are nothing but a client: every public object is the request.
NETWORK_CLIENT = {
    "Bio.KEGG.REST",
    "Bio.TogoWS",
    "Bio.UniProt",  # fetch_* only
    "Bio.Blast.NCBIWWW",  # qblast: the BLAST runs on NCBI's machines
    "Bio.PDB.PDBList",
    "Bio.PDB.alphafold_db",
    "Bio.ExPASy",  # the four get_* fetchers
}

# Modules that hold both a fetcher and a parser of files that fetcher brought
# back.  Only the fetcher is skipped; the parser is real work.
NETWORK_NAMES = {
    "Bio.Entrez": {"epost", "efetch", "esearch", "elink", "einfo", "esummary", "espell", "ecitmatch"},
    "Bio.ExPASy.ScanProsite": {"scan"},
}

# Modules filed under a network package whose objects all parse a *local* file.
# They are on the remaster; the reason column just says why the module name is
# misleading.  This set exists because the first draft of this script skipped
# them wholesale by module name, which is the greed the review is meant to
# catch: `Bio.SwissProt.parse` opens a file on disk, it does not call a server.
OFFLINE_PARSERS = {
    "Bio.ExPASy.Enzyme",
    "Bio.ExPASy.Prodoc",
    "Bio.ExPASy.Prosite",
    "Bio.ExPASy.cellosaurus",
    "Bio.ExPASy.ScanProsite",
    "Bio.KEGG.Enzyme",
    "Bio.KEGG.Compound",
    "Bio.KEGG.Gene",
    "Bio.KEGG.Map",
    "Bio.SwissProt",
    "Bio.SwissProt.KeyWList",
    "Bio.Medline",
    "Bio.UniGene",
    "Bio.Geo",
    "Bio.PDB.PICIO",  # reads and writes PIC directories, no server involved
    "Bio.Entrez.Parser",  # expat handlers over an XML document already in hand
}

# --- rule 4: the object's job is to launch another program -------------------
# Whole modules that exist only to drive an external binary.  Their `read()` is
# not a parser: it runs the program and parses what comes back.
SUBPROCESS = {
    "Bio.Emboss.PrimerSearch",
    "Bio.Emboss.Primer3",
    "Bio.Phylo.PAML._paml",
    "Bio.Phylo.PAML.codeml",
    "Bio.Phylo.PAML.baseml",
    "Bio.Phylo.PAML.yn00",
}

# Modules that are a launcher *and* a library of parsers and geometry: skip the
# entry points that shell out, keep the rest.  Named explicitly rather than by
# prefix, because `DSSP` and `NACCESS_atomic` launch the program from their
# constructors and carry no telltale prefix at all.
SUBPROCESS_HYBRID = {
    "Bio.PDB.DSSP": {"DSSP", "dssp_dict_from_pdb_file"},
    "Bio.PDB.NACCESS": {"run_naccess", "NACCESS", "NACCESS_atomic"},
    "Bio.PDB.ResidueDepth": {"get_surface", "ResidueDepth"},  # msms
    "Bio.PDB.PSEA": {"run_psea", "PSEA"},
}

# --- rule 7: the function's job is to draw, not to compute -------------------
# `xGC_skew` is the whole set today, and it was the one row this triage got
# wrong.  It imports tkinter, creates a `Canvas`, plots the two skew curves,
# calls `canvas.update()` and returns `None`: with `DISPLAY` set it takes 237 ms
# a call and there is no value to compare and no algorithm to port.  It was
# filed `perf` in the first pass and the SeqUtils work re-derived that by hand;
# a `perf` verdict here is a standing invitation to do it again.
GRAPHICS = {
    "Bio.SeqUtils": {"xGC_skew"},
}

# --- rule 5: upstream already implements it in C ----------------------------
ALREADY_C = {
    "Bio.Cluster",  # Bio.Cluster._cluster, kcluster/kmedoids/treecluster/pca
    "Bio.Cluster._cluster",
    "Bio.cpairwise2",
    "Bio.Nexus.cnexus",
    "Bio.PDB.qcprot",
    "Bio.PDB.ccealign",
}

# --- rule 2: deprecated in fact, not in the flag column ---------------------
DEPRECATED_MODULES = {
    "Bio.pairwise2",  # superseded upstream by Bio.Align.PairwiseAligner
}

# --- rule 6: the work belongs to a numerical library ------------------------
NUMERIC_LIBRARY = {
    "Bio.phenotype.pm_fitting",  # scipy.optimize.curve_fit
}

# --- data, not code ---------------------------------------------------------
DATA = {
    "Bio.Restriction.Restriction",  # 1,111 generated enzyme classes
    "Bio.Restriction.PrintFormat",  # the Restriction output surface
    "Bio.Data.CodonTable",
    "Bio.Align.substitution_matrices",
}

# --- hot paths: this is what the C core is for ------------------------------
PERF = {
    "Bio.Seq",
    "Bio.SeqRecord",
    "Bio.SeqIO.QualityIO",  # step 1.2
    "Bio.SeqIO.FastaIO",  # step 1.2
    "Bio.SeqIO._index",  # step 1.2, the .fai side
    "Bio.SeqUtils",
    "Bio.SeqUtils.ProtParam",
    "Bio.SeqUtils.IsoelectricPoint",
    "Bio.SeqUtils.MeltingTemp",
    "Bio.SeqUtils.CheckSum",
    "Bio.SeqUtils.lcc",
    "Bio.bgzf",  # block gzip: the BAM/BGZF path
    # Structure: coordinate math and traversal, megabytes of it per file.
    "Bio.PDB.vectors",
    "Bio.PDB.internal_coords",
    "Bio.PDB.ic_rebuild",
    "Bio.PDB.NeighborSearch",
    "Bio.PDB.SASA",
    "Bio.PDB.Superimposer",
    "Bio.PDB.SVDSuperimposer",
    "Bio.PDB.StructureAlignment",
    "Bio.PDB.cealign",
    "Bio.PDB.HSExposure",
    "Bio.PDB.Atom",
    "Bio.PDB.Entity",
    "Bio.PDB.Residue",
    "Bio.PDB.Chain",
    "Bio.PDB.Model",
    "Bio.PDB.Structure",
    "Bio.PDB.PDBParser",
    "Bio.PDB.MMCIFParser",
    "Bio.PDB.PDBMLParser",
    "Bio.PDB.MMCIF2Dict",
    "Bio.PDB.parse_pdb_header",
    # Alignment objects and the columnar formats that carry them.
    "Bio.Align",
    "Bio.Align.analysis",
    "Bio.Align.bigbed",
    "Bio.Align.interfaces",
    "Bio.motifs.matrix",  # PWM scoring
    "Bio.Phylo.TreeConstruction",
    "Bio.Phylo.Consensus",
}

REASONS = {
    "perf": "hot path: measured or structural speed gap, kernel candidate",
    "parity": "drop-in compatibility; small surface, no large win expected",
    "parity_offline": "parses a local file; the fetcher it is filed under lives elsewhere in the package",
    "data": "becomes data + a parser; no class port",
    "skip_deprecated": "deprecated upstream (inventory flag)",
    "skip_deprecated_module": "deprecated upstream in fact (not in the flag column)",
    "skip_network": "network transport: an HTTP request, nothing for C to speed up",
    "skip_subprocess": "launches an external program",
    "skip_already_c": "already implemented in C upstream -- reuse, do not rewrite",
    "skip_numeric_lib": "delegates the numerics to a third-party library",
    "skip_graphics": "draws a window and returns None; nothing to compare, nothing to port",
}


def verdict_for(row: dict[str, str]) -> tuple[str, str]:
    """Return (verdict, reason_key) for one inventory row."""
    module, name = row["module"], row["name"]

    if row["deprecated"] == "True":
        return "skip", "skip_deprecated"
    if module in DEPRECATED_MODULES:
        return "skip", "skip_deprecated_module"
    if module in ALREADY_C:
        return "skip", "skip_already_c"
    if module in NUMERIC_LIBRARY:
        return "skip", "skip_numeric_lib"
    # Name-level first: a mixed module's parser must not be caught by its
    # neighbour's rule.
    if name in NETWORK_NAMES.get(module, ()):
        return "skip", "skip_network"
    if module in NETWORK_CLIENT:
        return "skip", "skip_network"
    if module in SUBPROCESS:
        return "skip", "skip_subprocess"
    if name in SUBPROCESS_HYBRID.get(module, ()):
        return "skip", "skip_subprocess"
    if name in GRAPHICS.get(module, ()):
        return "skip", "skip_graphics"
    if module in OFFLINE_PARSERS:
        return "parity", "parity_offline"
    if module in DATA:
        return "data", "data"
    if module in PERF:
        return "perf", "perf"
    return "parity", "parity"


def main(argv: list[str]) -> int:
    if not SOURCE.exists():
        print(f"{SOURCE} not found -- run inventory/scan_biopython.py first", file=sys.stderr)
        return 1

    with SOURCE.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        print(f"{SOURCE} is empty", file=sys.stderr)
        return 1

    counts: Counter[str] = Counter()
    reasons: Counter[str] = Counter()
    skipped: dict[str, list[str]] = {}

    for row in rows:
        verdict, reason_key = verdict_for(row)
        row["verdict"] = verdict
        row["reason"] = REASONS[reason_key]
        counts[verdict] += 1
        reasons[reason_key] += 1
        if verdict == "skip":
            skipped.setdefault(reason_key, []).append(f"{row['module']}.{row['name']}")

    fields = list(rows[0].keys())
    with TARGET.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)

    total = len(rows)
    print(f"{total} rows -> {TARGET.name}\n")
    for verdict, count in counts.most_common():
        print(f"  {verdict:7s} {count:5d}  {100 * count / total:5.1f}%")
    print()
    for reason_key, count in reasons.most_common():
        print(f"  {reason_key:24s} {count:5d}  {REASONS[reason_key]}")
    print("\nskipped, in full -- this is the list to argue with:")
    for reason_key, names in skipped.items():
        print(f"\n  [{reason_key}] {len(names)} rows")
        for name in names:
            print(f"    {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
