"""Step 1.2: the FASTQ kernel, against Biopython's FastqGeneralIterator.

Two layers, and the split is deliberate.  The first layer asserts behaviour on
hand-written byte strings that need neither Biopython nor the generated corpus,
so CI -- which has neither -- still tests the kernel.  The second is the real
test: every file in the corpus, parsed twice and compared record for record.
A parser that agrees with itself is not evidence; a parser that agrees with the
reference on a corpus somebody else generated is.

One divergence is known and is not a bug: the reference reads a *text* stream,
so Biopython decodes the file (UTF-8 by default) before parsing it, and rejects
a file that is not valid UTF-8.  This kernel works on bytes and does not
decode.  Every file in the corpus is ASCII, which is what FASTQ is in practice,
and no test here feeds it anything else.
"""

import gzip
import importlib.util
import io
import random
from pathlib import Path

import pytest

import biofasting

DATA = Path(__file__).resolve().parent.parent / "bench" / "data"

# The corpus is generated by bench/gen_data.py and is not in git, so its
# absence is a skip and not a failure.
needs_corpus = pytest.mark.skipif(
    not (DATA / "fastq" / "reads_10k.fastq").exists(),
    reason="benchmark corpus not generated (python bench/gen_data.py)",
)
needs_biopython = pytest.mark.skipif(
    importlib.util.find_spec("Bio") is None,
    reason="Biopython is not installed; it is the differential reference",
)


def scan(data):
    """Run the kernel over `data`, letting a malformed input raise."""
    return list(biofasting._core.FastqScanner(data))


def mine(data):
    """Run the kernel over `data` and return (records, exception).

    The differential tests need both verdicts, not just the failure, so this
    one catches what `scan` lets through.
    """
    try:
        return scan(data), None
    except ValueError as exc:  # exactly the type the reference raises
        return None, exc


def reference(path):
    """Run Biopython the way the benchmark harness does, and report the same way."""
    from Bio.SeqIO.QualityIO import FastqGeneralIterator

    with open(path) as handle:
        try:
            records = [
                (t.encode(), s.encode(), q.encode())
                for t, s, q in FastqGeneralIterator(handle)
            ]
        except ValueError as exc:
            return None, exc
    return records, None


# --------------------------------------------------------------------------
# Behaviour, without the reference: what the kernel must do on inputs small
# enough to write out in full.
# --------------------------------------------------------------------------


def test_reads_a_plain_record():
    records, error = mine(b"@read1 comment\nACGT\n+\nIIII\n")
    assert error is None
    assert records == [(b"read1 comment", b"ACGT", b"IIII")]


def test_many_records_and_the_reported_positions():
    scanner = biofasting._core.FastqScanner(b"@a\nAC\n+\nII\n@b\nGT\n+\nJJ\n")
    assert next(scanner) == (b"a", b"AC", b"II")
    assert scanner.record_index == 1
    assert scanner.position == 11
    assert next(scanner) == (b"b", b"GT", b"JJ")
    assert scanner.position == 22
    with pytest.raises(StopIteration):
        next(scanner)


def test_an_empty_file_is_empty_and_not_an_error():
    records, error = mine(b"")
    assert error is None
    assert records == []


def test_a_blank_line_between_records_belongs_to_nobody():
    records, error = mine(b"@a\nAC\n+\nII\n\n\n@b\nGT\n+\nJJ\n")
    assert error is None
    assert records == [(b"a", b"AC", b"II"), (b"b", b"GT", b"JJ")]


def test_crlf_ends_a_line_like_the_text_stream_does():
    records, error = mine(b"@a note\r\nAC\r\n+\r\nII\r\n@b\r\nGT\r\n+\r\nJJ\r\n")
    assert error is None
    assert records == [(b"a note", b"AC", b"II"), (b"b", b"GT", b"JJ")]


def test_a_lone_carriage_return_also_ends_a_line():
    # Python's universal newlines, which is the stream Biopython is given.
    records, error = mine(b"@a\rAC\r+\rII\r@b\rGT\r+\rJJ\r")
    assert error is None
    assert records == [(b"a", b"AC", b"II"), (b"b", b"GT", b"JJ")]


def test_wrapped_sequence_and_quality_are_concatenated():
    records, error = mine(b"@a\nACGT\nACGT\n+\nIIII\nJJJJ\n")
    assert error is None
    assert records == [(b"a", b"ACGTACGT", b"IIIIJJJJ")]


def test_a_quality_line_may_start_with_at():
    # The whole reason the parser tracks the sequence length: scanning for '@'
    # to find the next header corrupts this record.
    records, error = mine(b"@a\nACGT\n+\n@@@@\n@b\nTT\n+\nII\n")
    assert error is None
    assert records == [(b"a", b"ACGT", b"@@@@"), (b"b", b"TT", b"II")]


def test_a_quality_line_may_start_with_plus():
    records, error = mine(b"@a\nACGT\n+\n++II\n")
    assert error is None
    assert records == [(b"a", b"ACGT", b"++II")]


def test_the_plus_line_may_repeat_the_title():
    records, error = mine(b"@a note\nACGT\n+a note\nIIII\n")
    assert error is None
    assert records == [(b"a note", b"ACGT", b"IIII")]


def test_the_plus_line_must_match_when_it_is_present():
    with pytest.raises(ValueError, match="Sequence and quality captions differ."):
        scan(b"@a\nACGT\n+b\nIIII\n")


def test_an_empty_sequence_is_a_record_too():
    records, error = mine(b"@empty\n\n+\n\n@next\nAC\n+\nII\n")
    assert error is None
    assert records == [(b"empty", b"", b""), (b"next", b"AC", b"II")]


def test_trailing_whitespace_is_stripped_not_an_error():
    # rstrip happens per line, before the whitespace check, so padding before
    # the line break is invisible while an interior space is not.
    records, error = mine(b"@a  \nACGT  \n+\nIIII  \n")
    assert error is None
    assert records == [(b"a", b"ACGT", b"IIII")]


def test_a_space_inside_the_sequence_is_rejected():
    with pytest.raises(ValueError, match="Whitespace is not allowed"):
        scan(b"@a\nAC GT\n+\nIIIII\n")


def test_a_tab_inside_the_sequence_is_rejected():
    with pytest.raises(ValueError, match="Whitespace is not allowed"):
        scan(b"@a\nAC\tGT\n+\nIIIII\n")


def test_a_file_that_does_not_start_with_at_is_rejected():
    with pytest.raises(ValueError, match="should start with '@'"):
        scan(b"ACGT\n+\nIIII\n")


def test_a_header_without_a_record_is_rejected():
    with pytest.raises(ValueError, match="Unexpected end of file"):
        scan(b"@a\n")


def test_a_missing_plus_line_is_rejected():
    with pytest.raises(ValueError, match="End of file without quality information."):
        scan(b"@a\nACGT\nIIII\n")


def test_a_short_quality_is_rejected():
    with pytest.raises(
        ValueError, match=r"Lengths of sequence and quality values differs for a "
    ):
        scan(b"@a\nACGT\n+\nII\n")


def test_a_long_quality_is_rejected():
    with pytest.raises(ValueError, match="Lengths of sequence and quality"):
        scan(b"@a\nACGT\n+\nIIIIII\n")


def test_the_error_carries_the_location_biopython_cannot_give():
    # 15 bytes of a good record, then a bad one: the message says where.
    with pytest.raises(ValueError, match=r"record 1, byte offset 15"):
        scan(b"@a\nACGT\n+\nIIII\n@b\nTTTT\n+\nJJ\n")


def test_a_hundred_thousand_records_in_one_buffer():
    data = b"".join(b"@r%d\nACGTACGT\n+\nIIIIIIII\n" % i for i in range(100_000))
    records, error = mine(data)
    assert error is None
    assert len(records) == 100_000
    assert records[-1] == (b"r99999", b"ACGTACGT", b"IIIIIIII")


def test_the_file_helper_maps_and_iterates(tmp_path):
    path = tmp_path / "reads.fastq"
    path.write_bytes(b"@a\nACGT\n+\nIIII\n")
    assert list(biofasting.open_fastq(path)) == [(b"a", b"ACGT", b"IIII")]
    assert biofasting.scan_fastq(path) == [(b"a", b"ACGT", b"IIII")]


def test_the_file_helper_handles_an_empty_file(tmp_path):
    path = tmp_path / "empty.fastq"
    path.write_bytes(b"")
    assert biofasting.scan_fastq(path) == []


def test_the_file_helper_refuses_a_non_buffer(tmp_path):
    with pytest.raises(TypeError):
        biofasting._core.FastqScanner(42)


# --------------------------------------------------------------------------
# gzip.  The format is detected by its magic bytes rather than by the file
# name, so these all go through the same entry point as a plain file.
# --------------------------------------------------------------------------


def test_a_gzipped_file_is_read_transparently(tmp_path):
    path = tmp_path / "reads.fastq.gz"
    path.write_bytes(gzip.compress(b"@a\nACGT\n+\nIIII\n@b\nGT\n+\nJJ\n"))
    assert biofasting.scan_fastq(path) == [
        (b"a", b"ACGT", b"IIII"),
        (b"b", b"GT", b"JJ"),
    ]


def test_a_plain_file_is_not_mistaken_for_gzip(tmp_path):
    # A 1-byte file is short enough to trip a naive bounds check on the magic.
    path = tmp_path / "one.fastq"
    path.write_bytes(b"@")
    with pytest.raises(ValueError):
        biofasting.scan_fastq(path)


def test_concatenated_gzip_members_are_all_read(tmp_path):
    # `gzip -c a b > ab.gz` produces two members, and both are valid input.
    path = tmp_path / "two.fastq.gz"
    path.write_bytes(
        gzip.compress(b"@a\nACGT\n+\nIIII\n") + gzip.compress(b"@b\nGT\n+\nJJ\n")
    )
    assert biofasting.scan_fastq(path) == [
        (b"a", b"ACGT", b"IIII"),
        (b"b", b"GT", b"JJ"),
    ]


def test_a_record_may_span_two_gzip_members(tmp_path):
    # Legal in the format and produced by parallel compressors, which is not a
    # hypothetical: it is why the members are concatenated before scanning
    # rather than scanned one at a time.
    path = tmp_path / "split.fastq.gz"
    path.write_bytes(gzip.compress(b"@a\nACGT\n") + gzip.compress(b"+\nIIII\n"))
    assert biofasting.scan_fastq(path) == [(b"a", b"ACGT", b"IIII")]


def test_a_corrupt_gzip_stream_is_rejected(tmp_path):
    data = bytearray(gzip.compress(b"@a\nACGT\n+\nIIII\n" * 50))
    data[len(data) // 2] ^= 0xFF
    path = tmp_path / "corrupt.fastq.gz"
    path.write_bytes(bytes(data))
    with pytest.raises(ValueError):
        biofasting.scan_fastq(path)


def test_trailing_bytes_after_the_last_gzip_member_are_rejected(tmp_path):
    # Python's gzip module ignores them; accepting a file whose tail nobody can
    # account for is the kind of quiet correctness failure this suite exists to
    # refuse.
    path = tmp_path / "trailing.fastq.gz"
    path.write_bytes(gzip.compress(b"@a\nACGT\n+\nIIII\n") + b"garbage")
    with pytest.raises(ValueError):
        biofasting.scan_fastq(path)


# --------------------------------------------------------------------------
# Differential: the corpus, parsed twice.
# --------------------------------------------------------------------------

GOOD_FASTQ = [
    "fastq/reads_10k.fastq",
    "edge/blank_lines.fastq",
    "edge/crlf.fastq",
    "edge/empty_file.fastq",
    "edge/empty_read.fastq",
    "edge/full_quality_range.fastq",
    "edge/long_read.fastq",
    "edge/multiline.fastq",
    "edge/no_trailing_newline.fastq",
    "edge/phred64.fastq",
    "edge/quality_contains_at_and_plus.fastq",
]

BAD_FASTQ = [
    "malformed/header_only.fastq",
    "malformed/length_mismatch.fastq",
    "malformed/missing_plus_line.fastq",
    "malformed/truncated_mid_quality.fastq",
]


@needs_biopython
@needs_corpus
@pytest.mark.parametrize("relative", GOOD_FASTQ)
def test_the_corpus_parses_identically(relative):
    path = DATA / relative
    expected, expected_error = reference(path)
    assert expected_error is None, f"the reference rejected {relative}"
    actual, actual_error = mine(path.read_bytes())
    assert actual_error is None
    assert actual == expected


@needs_biopython
@needs_corpus
@pytest.mark.parametrize("relative", BAD_FASTQ)
def test_the_corpus_is_rejected_by_both(relative):
    path = DATA / relative
    expected, expected_error = reference(path)
    actual, actual_error = mine(path.read_bytes())
    # Same verdict on every file: the reference refuses it, so this must too.
    assert (expected_error is None) == (actual_error is None), (
        f"{relative}: reference error={expected_error!r}, ours={actual_error!r}"
    )
    assert actual_error is not None


@needs_biopython
@needs_corpus
def test_the_million_read_corpus_parses_identically():
    """The file the benchmark actually measures, record for record.

    Not a speed test -- the numbers live in the bench.  This is the evidence
    that the fast path, which is the only path this file takes, returns the
    same bytes as the reference on all one million records.
    """
    from Bio.SeqIO.QualityIO import FastqGeneralIterator

    path = DATA / "fastq" / "reads_1m.fastq"
    scanner = biofasting.open_fastq(path)
    with open(path) as handle:
        expected_count = 0
        for expected in FastqGeneralIterator(handle):
            title, sequence, quality = next(scanner)
            assert title == expected[0].encode()
            assert sequence == expected[1].encode()
            assert quality == expected[2].encode()
            expected_count += 1
    assert expected_count == 1_000_000
    with pytest.raises(StopIteration):
        next(scanner)


@needs_biopython
@needs_corpus
def test_the_million_read_corpus_parses_identically_gzipped():
    """The same reads, compressed, through the inflate path.

    Diffed against the same reference the benchmark uses for a .gz row --
    `gzip.open()` in text mode -- so this covers the decompressor and the
    scanner together rather than the scanner twice.
    """
    from Bio.SeqIO.QualityIO import FastqGeneralIterator

    path = DATA / "fastq" / "reads_1m.fastq.gz"
    scanner = biofasting.open_fastq(path)
    with gzip.open(path, "rt") as handle:
        expected_count = 0
        for expected in FastqGeneralIterator(handle):
            title, sequence, quality = next(scanner)
            assert title == expected[0].encode()
            assert sequence == expected[1].encode()
            assert quality == expected[2].encode()
            expected_count += 1
    assert expected_count == 1_000_000
    with pytest.raises(StopIteration):
        next(scanner)


@needs_corpus
def test_the_gzipped_corpus_matches_the_plain_one():
    """The two corpus files are the same reads; this says so independently of
    the reference, so the gz evidence survives Biopython being unavailable."""
    plain = biofasting.open_fastq(DATA / "fastq" / "reads_10k.fastq")
    compressed = biofasting.open_fastq(DATA / "fastq" / "reads_1m.fastq.gz")
    for _, expected in zip(range(10_000), plain):
        assert next(compressed) == expected


# --------------------------------------------------------------------------
# Fuzz: inputs nobody wrote by hand.
# --------------------------------------------------------------------------

ALPHABET = b"@+ACGT \t\r\n"


def reference_bytes(data: bytes):
    """The reference's verdict on raw bytes: records, or the exception."""
    from Bio.SeqIO.QualityIO import FastqGeneralIterator

    handle = io.StringIO(data.decode("ascii"), newline=None)
    try:
        return [
            (t.encode(), s.encode(), q.encode()) for t, s, q in FastqGeneralIterator(handle)
        ], None
    except ValueError as exc:
        return None, exc


@needs_biopython
@pytest.mark.parametrize("seed", range(8))
def test_random_input_gets_the_same_verdict(seed):
    """Random line-shaped text, both parsers, same answer.

    The generator is seeded and the alphabet is deliberately nasty: '@' and '+'
    are in it because they are the two characters that decide where a record
    ends, and so are spaces, tabs and both line endings.  Only ASCII is fed in,
    because the reference decodes and this kernel does not.
    """
    rng = random.Random(seed)
    for _ in range(300):
        lines = [
            bytes(rng.choice(ALPHABET) for _ in range(rng.randrange(0, 12)))
            for _ in range(rng.randrange(1, 14))
        ]
        data = b"\n".join(lines) + rng.choice([b"", b"\n"])
        expected, expected_error = reference_bytes(data)
        actual, actual_error = mine(data)
        assert (expected_error is None) == (actual_error is None), (
            f"seed={seed} data={data!r}\n"
            f"reference={expected_error!r}\nours={actual_error!r}"
        )
        assert actual == expected, f"seed={seed} data={data!r}"
