"""Step 1.3: the zero-copy views, which are the reason numpy is a dependency.

A view is a claim about memory, and the only way to test a claim about memory
is to look at the memory rather than at the values.  So the central test here
is not "the array equals the file" -- a copy would pass that -- but the
mutation test: build the grid over a writable buffer, change a byte in the
buffer, and require the array to change with it.  A copy cannot do that.

The second thing this file pins down is the *refusal*.  A grid is only sound
when every record has the same shape, so the reader checks all of them and
raises on the first that does not.  The corpus turns out to exercise both
sides: the genome is a perfect grid and the FASTQ files are not, because their
headers vary in width.  Both facts are asserted below, including the one that
costs us a speedup, because a suite that only tests the happy path is a suite
that will one day report a wrong answer as a fast one.

The corpus is generated by bench/gen_data.py and is not in git, so its absence
is a skip; numpy is a declared dependency now, and the skip below is only for
the case of an extension copied out of its wheel into an environment that
never installed it.
"""

import gc
import gzip
import random
from pathlib import Path

import pytest

import biofasting

numpy = pytest.importorskip("numpy")

DATA = Path(__file__).resolve().parent.parent / "bench" / "data"

needs_corpus = pytest.mark.skipif(
    not (DATA / "fasta" / "genome.fasta").exists(),
    reason="benchmark corpus not generated (python bench/gen_data.py)",
)
def uniform_fastq(records, length=8, title_width=6):
    """Build a FASTQ file whose every record has the same shape."""
    out = []
    for index in range(records):
        title = ("r%d" % index).ljust(title_width, "x")
        out.append(b"@%s\n%s\n+\n%s\n" % (title.encode(), b"ACGT" * (length // 4), b"I" * length))
    return b"".join(out)


# --------------------------------------------------------------------------
# FASTQ: two strided arrays.
# --------------------------------------------------------------------------


def test_a_uniform_file_becomes_two_strided_arrays(tmp_path):
    path = tmp_path / "reads.fastq"
    path.write_bytes(uniform_fastq(3, length=8, title_width=6))
    grid = biofasting.open_fastq_grid(path)
    assert grid.sequences.shape == (3, 8)
    assert grid.qualities.shape == (3, 8)
    assert grid.sequences.dtype == numpy.uint8
    assert grid.qualities.dtype == numpy.uint8
    # Header bytes from the record's start to its sequence, '@' included: it is
    # the piece of the stride the two arrays do not account for.
    assert grid.title_length == 7
    # A record is not one line's worth of bytes, so the row stride is longer
    # than the row: this is the whole point of a strided view.
    assert grid.sequences.strides == (grid.sequences.strides[0], 1)
    assert grid.sequences.strides[0] > grid.sequences.shape[1]
    assert grid.sequences[0].tobytes() == b"ACGTACGT"
    assert grid.qualities[2].tobytes() == b"IIIIIIII"


def test_the_rows_are_the_records_of_the_file(tmp_path):
    """The view against the streaming reader, on input neither of them wrote."""
    rng = random.Random(11)
    lines = []
    for index in range(200):
        title = ("read%d" % index).ljust(9, "_").encode()
        sequence = bytes(rng.choice(b"ACGT") for _ in range(32))
        quality = bytes(rng.randrange(33, 74) for _ in range(32))
        lines.append(b"@%s\n%s\n+\n%s\n" % (title, sequence, quality))
    path = tmp_path / "reads.fastq"
    path.write_bytes(b"".join(lines))

    grid = biofasting.open_fastq_grid(path)
    records = biofasting.scan_fastq(path)
    assert grid.sequences.shape == (200, 32)
    for row, (title, sequence, quality) in enumerate(records):
        assert grid.sequences[row].tobytes() == sequence
        assert grid.qualities[row].tobytes() == quality
        assert len(title) + 1 == grid.title_length


def test_the_arrays_are_read_only(tmp_path):
    path = tmp_path / "reads.fastq"
    path.write_bytes(uniform_fastq(2))
    grid = biofasting.open_fastq_grid(path)
    assert not grid.sequences.flags.writeable
    with pytest.raises(ValueError):
        grid.sequences[0, 0] = 84


def test_the_arrays_are_views_and_not_copies():
    """The mutation test: only a view of the buffer can follow a change to it.

    A bytearray is used because a mapped file is read-only and cannot be
    changed under the array -- which is the whole reason the reader is built
    over an arbitrary buffer rather than over a path.
    """
    data = bytearray(uniform_fastq(2, length=4, title_width=2))
    scanner = biofasting._core.FastqScanner(data)
    sequences, _, _ = scanner.grid()
    assert sequences[0].tobytes() == b"ACGT"
    data[data.index(b"ACGT")] = ord("T")
    assert sequences[0].tobytes() == b"TCGT"


def test_a_ragged_sequence_length_is_refused(tmp_path):
    path = tmp_path / "ragged.fastq"
    path.write_bytes(b"@a\nACGT\n+\nIIII\n@b\nACG\n+\nIII\n")
    with pytest.raises(ValueError, match="record 1"):
        biofasting.open_fastq_grid(path)


def test_a_ragged_header_length_is_refused(tmp_path):
    # Same shape everywhere except the title: a numpy view needs a constant
    # stride, and the title is part of the stride.
    path = tmp_path / "ragged.fastq"
    path.write_bytes(b"@a\nACGT\n+\nIIII\n@longer\nACGT\n+\nIIII\n")
    with pytest.raises(ValueError, match="record 1"):
        biofasting.open_fastq_grid(path)


def test_a_gzipped_file_is_a_grid_too(tmp_path):
    path = tmp_path / "reads.fastq.gz"
    path.write_bytes(gzip.compress(uniform_fastq(4, length=4, title_width=2)))
    grid = biofasting.open_fastq_grid(path)
    assert grid.sequences.shape == (4, 4)
    assert grid.sequences[3].tobytes() == b"ACGT"


def test_an_empty_file_is_an_empty_grid(tmp_path):
    path = tmp_path / "empty.fastq"
    path.write_bytes(b"")
    grid = biofasting.open_fastq_grid(path)
    assert grid.sequences.shape == (0, 0)
    assert grid.qualities.shape == (0, 0)
    assert grid.title_length == 0


def test_the_fastq_grid_keeps_the_mapping_alive(tmp_path):
    """Only the returned arrays outlive the call, so only they can hold it.

    The file is dropped, then collected, then read: if the mapping were owned
    by anything that died at the end of `open_fastq_grid`, this would read
    freed memory rather than the file's bytes.
    """
    path = tmp_path / "reads.fastq"
    path.write_bytes(uniform_fastq(2, length=4, title_width=2))
    grid = biofasting.open_fastq_grid(path)
    del path
    gc.collect()
    assert grid.sequences[1].tobytes() == b"ACGT"
    assert grid.qualities[0].tobytes() == b"IIII"


# --------------------------------------------------------------------------
# FASTA: one strided array per record, and a length that can exceed it.
# --------------------------------------------------------------------------


def test_a_uniform_record_becomes_a_strided_array(tmp_path):
    path = tmp_path / "ref.fasta"
    path.write_bytes(b">r1\nACGTAC\nGTACGT\nACGTAC\n")
    grid = biofasting.open_fasta_grid(path, "r1")
    assert grid.bases.shape == (3, 6)
    assert grid.bases.dtype == numpy.uint8
    assert grid.bases.strides == (7, 1)
    assert grid.length == 18
    assert grid.bases.tobytes() == b"ACGTACGTACGTACGTAC"
    assert [row.tobytes() for row in grid.bases] == [b"ACGTAC", b"GTACGT", b"ACGTAC"]


def test_a_short_last_line_is_visible_as_a_shorter_size(tmp_path):
    """The tail is not silently dropped: `length` is the record's real length.

    An 8-base record written three to a line ends with a 2-base line, which
    cannot live in a (lines, 3) array.  The array therefore covers 6 of the 8
    bases and says so, and the remainder is one indexed slice away.
    """
    path = tmp_path / "ref.fasta"
    path.write_bytes(b">r1\nACG\nTAC\nGT\n")
    grid = biofasting.open_fasta_grid(path, "r1")
    assert grid.bases.shape == (2, 3)
    assert grid.bases.size == 6
    assert grid.length == 8
    assert grid.bases.tobytes() == b"ACGTAC"
    tail = biofasting.open_fasta(path).sequence_slice("r1", grid.bases.size, grid.length)
    assert tail == b"GT"


def test_a_single_line_record_is_one_row(tmp_path):
    path = tmp_path / "ref.fasta"
    path.write_bytes(b">r1\nACGTACGT\n")
    grid = biofasting.open_fasta_grid(path, "r1")
    assert grid.bases.shape == (1, 8)
    assert grid.length == 8
    assert grid.bases[0].tobytes() == b"ACGTACGT"


def test_a_record_that_changes_its_line_width_is_refused(tmp_path):
    path = tmp_path / "ragged.fasta"
    path.write_bytes(b">r1\nACGTAC\nGTACGTAC\n")
    with pytest.raises(ValueError, match="r1"):
        biofasting.open_fasta_grid(path, "r1")


def test_the_arrays_are_read_only_and_are_views(tmp_path):
    path = tmp_path / "ref.fasta"
    path.write_bytes(b">r1\nACGTAC\nGTACGT\n")
    grid = biofasting.open_fasta_grid(path, "r1")
    assert not grid.bases.flags.writeable
    with pytest.raises(ValueError):
        grid.bases[0, 0] = 84

    # The same mutation test as the FASTQ side, over a writable buffer.
    data = bytearray(b">r1\nACGTAC\nGTACGT\n")
    bases, _ = biofasting._core.FastaIndex(data).grid("r1")
    assert bases[0].tobytes() == b"ACGTAC"
    data[4] = ord("T")
    assert bases[0].tobytes() == b"TCGTAC"


def test_the_fasta_grid_keeps_the_mapping_alive(tmp_path):
    path = tmp_path / "ref.fasta"
    path.write_bytes(b">r1\nACGTAC\nGTACGT\n")
    grid = biofasting.open_fasta_grid(path, "r1")
    del path
    gc.collect()
    assert grid.bases[1].tobytes() == b"GTACGT"


# --------------------------------------------------------------------------
# The corpus.  One of these two files is a grid and one is not, and the suite
# says which rather than the README.
# --------------------------------------------------------------------------


@needs_corpus
def test_the_corpus_genome_is_a_grid():
    """chr1 is 40 Mbp at 60 bases a line, so it is a (666666, 60) view.

    Checked on both ends against the index's own copy of the bytes, so the
    view is pinned to the reader rather than to a number written here, and the
    40-base final line is asserted to be exactly the difference between the
    array's size and the record's length.
    """
    path = DATA / "fasta" / "genome.fasta"
    index = biofasting.open_fasta(path)
    grid = biofasting.open_fasta_grid(path, "chr1")
    assert grid.bases.shape == (666_666, 60)
    assert grid.bases.strides == (61, 1)
    assert grid.length == 40_000_000
    assert grid.bases.size == 39_999_960
    flat = numpy.ascontiguousarray(grid.bases).reshape(-1)
    assert flat[:1_000].tobytes() == index["chr1"][:1_000]
    assert flat[-60:].tobytes() == index.sequence_slice("chr1", 39_999_900, 39_999_960)
    assert index.sequence_slice("chr1", grid.bases.size, grid.length) == (
        b"TTTAGCCTCATAACAATAATTAATCTTTCTGACGCATGCA"
    )


@needs_corpus
def test_the_corpus_reads_are_not_a_grid_and_that_is_the_finding():
    """Both corpus FASTQ files have variable-width headers, so neither is.

    This is the honest half of the step: a zero-copy view of a read file is
    impossible without copying the titles out, and the reader says so instead
    of returning an array with the wrong stride.  The benchmark report carries
    the same finding, because it is why the FASTQ grid does not appear in the
    speed-up table.
    """
    for relative in ("fastq/reads_10k.fastq", "fastq/reads_1m.fastq"):
        path = DATA / relative
        if not path.exists():
            pytest.skip(f"{relative} is not in the corpus")
        with pytest.raises(ValueError, match="record 1 does not have the same shape"):
            biofasting.open_fastq_grid(path)
        # The same files are still read, by the reader that does not need a
        # constant stride -- one record is enough to say so, and the million
        # read file is not materialised here for a test about its stride.
        title, sequence, quality = next(biofasting.open_fastq(path))
        assert title and len(sequence) == len(quality)
